export interface ShellInitOptions {
  readonly mappingFile: string;
  readonly caseInsensitive: boolean;
}

export const zshSnippet = (options: ShellInitOptions): string => {
  const fold = options.caseInsensitive;
  const target = fold ? "${root:l}" : "$root";
  const cand = fold ? "${p:l}" : "$p";

  return `# git-user-mapper shell integration (zsh)
# Generated by \`git-mapper shell-init zsh\`. The table itself is read on every prompt,
# so only regenerate this if the mapping file path changes.
_git_mapper_file='${options.mappingFile}'

_git_mapper_resolve() {
  typeset -g GIT_MAPPER_PROFILE='' GIT_MAPPER_STATE='' GIT_MAPPER_COLOR=''

  local root='' d=\${PWD:A}
  while true; do
    if [[ -e $d/.git ]]; then root=$d; break; fi
    [[ $d == / ]] && break
    d=\${d:h}
  done
  [[ -n $root ]] || return 1
  [[ -r $_git_mapper_file ]] || return 1

  local line p rest pid color email cand
  local best_id='' best_color='' best_email='' best_len=-1
  local fb_id='' fb_color='' fb_email=''
  local target=${target}

  for line in \${(f)"$(<$_git_mapper_file)"}; do
    p=\${line%%$'\\t'*}
    rest=\${line#*$'\\t'}
    pid=\${rest%%$'\\t'*}
    rest=\${rest#*$'\\t'}
    color=\${rest%%$'\\t'*}
    email=\${rest#*$'\\t'}
    if [[ $p == '*' ]]; then
      fb_id=$pid fb_color=$color fb_email=$email
      continue
    fi
    cand=${cand}
    if [[ $target == "$cand" || $target == "$cand"/* ]] && (( $#p > best_len )); then
      best_id=$pid best_color=$color best_email=$email best_len=$#p
    fi
  done

  local applied_id applied_email applied_color state
  if (( best_len >= 0 )); then
    applied_id=$best_id applied_email=$best_email applied_color=$best_color state=mapped
  elif [[ -n $fb_id ]]; then
    applied_id=$fb_id applied_email=$fb_email applied_color=$fb_color state=default
  else
    GIT_MAPPER_STATE='no-identity'
    return 0
  fi

  local local_email='' cfg_line section=''
  if [[ -d $root/.git && -r $root/.git/config ]]; then
    for cfg_line in \${(f)"$(<$root/.git/config)"}; do
      cfg_line=\${cfg_line//[[:blank:]]/}
      case $cfg_line in
        '[user]') section=user ;;
        '['*) section='' ;;
        'email='*) [[ $section == user ]] && local_email=\${cfg_line#email=} ;;
      esac
    done
  fi

  if [[ -n $local_email && $local_email != $applied_email ]]; then
    GIT_MAPPER_STATE='local-override'
    GIT_MAPPER_PROFILE=$local_email
    GIT_MAPPER_COLOR=yellow
  else
    GIT_MAPPER_STATE=$state
    GIT_MAPPER_PROFILE=$applied_id
    GIT_MAPPER_COLOR=$applied_color
  fi
  return 0
}

# Powerlevel10k segment. Add \`git_mapper\` to POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS.
function prompt_git_mapper() {
  _git_mapper_resolve || return
  case $GIT_MAPPER_STATE in
    mapped)         p10k segment -f $GIT_MAPPER_COLOR -i '👤' -t "$GIT_MAPPER_PROFILE" ;;
    default)        p10k segment -e -f $GIT_MAPPER_COLOR -i '👤' -t "$GIT_MAPPER_PROFILE %F{244}(default)%f" ;;
    local-override) p10k segment -f yellow -i '⚠' -t "local: $GIT_MAPPER_PROFILE" ;;
    no-identity)    p10k segment -f red -i '⚠' -t 'no identity' ;;
  esac
}
function instant_prompt_git_mapper() { prompt_git_mapper }

# For themes other than p10k: \$GIT_MAPPER_PROFILE and \$GIT_MAPPER_STATE are refreshed
# before every prompt, so you can interpolate them into your own PROMPT.
_git_mapper_precmd() { _git_mapper_resolve }
autoload -Uz add-zsh-hook
add-zsh-hook precmd _git_mapper_precmd
`;
};
