import { posixSingleQuote } from "./quote.ts";
import {
  CONFIG_FN,
  GITDIR_FN,
  LOCAL_EMAIL_FN,
  LOWER_FN,
  NORMALIZE_FN,
  VALUE_FN,
} from "./snippet.ts";

export interface ShellInitOptions {
  readonly mappingFile: string;
  readonly caseInsensitive: boolean;
}

export const zshSnippet = (options: ShellInitOptions): string => {
  const fold = options.caseInsensitive;
  const target = fold ? '_git_mapper_lower "$_gm_gitdir"\n  target=$REPLY' : "target=$_gm_gitdir";
  const cand = fold ? '_git_mapper_lower "$p"; cand=$REPLY' : "cand=$p";

  return `# git-user-mapper shell integration (zsh)
# Generated by \`git-mapper shell-init zsh\`. The table itself is read on every prompt,
# so only regenerate this if the mapping file path changes.
_git_mapper_file=${posixSingleQuote(options.mappingFile)}

${LOWER_FN}

${NORMALIZE_FN}

${GITDIR_FN}

${VALUE_FN}

${CONFIG_FN}

${LOCAL_EMAIL_FN}

_git_mapper_resolve() {
  # 사용자의 setopt에 휘둘리지 않도록 함수 안에서만 기본값으로 되돌린다.
  # 예를 들어 globsubst가 켜져 있으면 표의 각 줄이 글롭으로 확장되어 매 프롬프트마다
  # "no matches found"가 뜬다. localoptions라 여기서 부르는 보조 함수까지 함께 적용된다.
  emulate -L zsh

  typeset -g GIT_MAPPER_PROFILE='' GIT_MAPPER_STATE='' GIT_MAPPER_COLOR=''

  # 보조 함수들이 값을 돌려주는 자리. local이라 사용자 환경에 남지 않는다.
  local REPLY='' _gm_gitdir='' _gm_commondir='' _gm_email='' _gm_worktree_config=''

  local root='' d=\${PWD:A}
  while true; do
    if [[ -e $d/.git ]]; then root=$d; break; fi
    [[ $d == / ]] && break
    d=\${d:h}
  done
  [[ -n $root ]] || return 1

  # git이 실제로 보는 GIT_DIR을 먼저 찾는다. 매핑 판정은 작업 트리가 아니라 이걸로 한다.
  _git_mapper_gitdir "$root" || return 1

  # 저장소의 로컬 [user]를 **먼저** 읽는다. 표에 아무 답이 없더라도 이 값이 있으면
  # git은 그걸로 커밋한다. 나중에 읽으면 "identity 없음"이라고 먼저 단정하게 된다.
  _git_mapper_local_email
  local local_email=$_gm_email

  local line p rest pid color email cand target
  local best_id='' best_color='' best_email='' best_len=-1
  local fb_id='' fb_color='' fb_email=''
  ${target}

  if [[ -r $_git_mapper_file ]]; then
    for line in \${(f)"$(<$_git_mapper_file)"}; do
      p=\${line%%$'\\t'*}
      rest=\${line#*$'\\t'}
      pid=\${rest%%$'\\t'*}
      rest=\${rest#*$'\\t'}
      color=\${rest%%$'\\t'*}
      email=\${rest#*$'\\t'}
      if [[ $p == '*' ]]; then
        fb_id=$pid fb_color=$color fb_email=$email
        continue
      fi
      ${cand}
      if [[ $target == "$cand" || $target == "$cand"/* ]] && (( $#p > best_len )); then
        best_id=$pid best_color=$color best_email=$email best_len=$#p
      fi
    done
  fi

  local applied_id='' applied_email='' applied_color='' state=''
  if (( best_len >= 0 )); then
    applied_id=$best_id applied_email=$best_email applied_color=$best_color state=mapped
  elif [[ -n $fb_id ]]; then
    applied_id=$fb_id applied_email=$fb_email applied_color=$fb_color state=default
  fi

  if [[ -n $local_email && $local_email != $applied_email ]]; then
    GIT_MAPPER_STATE='local-override'
    GIT_MAPPER_PROFILE=$local_email
    GIT_MAPPER_COLOR=yellow
  elif [[ -z $state ]]; then
    GIT_MAPPER_STATE='no-identity'
  else
    GIT_MAPPER_STATE=$state
    GIT_MAPPER_PROFILE=$applied_id
    GIT_MAPPER_COLOR=$applied_color
  fi
  return 0
}

# Powerlevel10k segment. Add \`git_mapper\` to POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS.
function prompt_git_mapper() {
  _git_mapper_resolve || return
  case $GIT_MAPPER_STATE in
    mapped)         p10k segment -f $GIT_MAPPER_COLOR -i '👤' -t "$GIT_MAPPER_PROFILE" ;;
    default)        p10k segment -e -f $GIT_MAPPER_COLOR -i '👤' -t "$GIT_MAPPER_PROFILE %F{244}(default)%f" ;;
    local-override) p10k segment -f yellow -i '⚠' -t "local: $GIT_MAPPER_PROFILE" ;;
    no-identity)    p10k segment -f red -i '⚠' -t 'no identity' ;;
  esac
}
function instant_prompt_git_mapper() { prompt_git_mapper }

# For themes other than p10k: $GIT_MAPPER_PROFILE and $GIT_MAPPER_STATE are refreshed
# before every prompt, so you can interpolate them into your own PROMPT.
_git_mapper_precmd() {
  # p10k 세그먼트가 이미 해석했다면 같은 프롬프트에서 두 번 돌 이유가 없다.
  if (( \${+functions[p10k]} )); then
    [[ \${POWERLEVEL9K_LEFT_PROMPT_ELEMENTS[(r)git_mapper]}\${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[(r)git_mapper]} == git_mapper ]] && return
  fi
  _git_mapper_resolve
}
autoload -Uz add-zsh-hook
add-zsh-hook precmd _git_mapper_precmd
`;
};
